# コメント略
default: &default
   adapter: mysql2
   encoding: utf8
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   username: root
   password:
   host: localhost

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fudgement_development
  pool: 5
  username: yamken
  password: yamken
  host: localhost

test:
  <<: *default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fudgement_test
  pool: 5
  username: yamken
  password: yamken
  host: localhost
 
production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
